services:
  postgres:
    image: postgres:16.1-alpine3.17
    environment:
      POSTGRES_DB: "PeoplesCats"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"